### ISSUE TITLE
bundles.py doesn't be imported from app.py in sample code

### ISSUE THREAD

**Issue by yohei-ocean** [inveniosoftware/invenio-previewer#78]
Dear colleague,

I am  trying to do invenio-previewer's example/app.py tutorial.
https://github.com/inveniosoftware/invenio-previewer/blob/master/examples/app.py

But 'flusk npm' command make just only  'package.json' with angular.
There aren't any bundle.py's npm settings in the package.json.

So, I added code like this to import the npm assets according to invenio-assets usage .

examples/app.py

    import invenio_previewer from bundles
    assets = InvenioAssets(app)
    assets.env.register( 'csv_previewer_js', bundles.csv_previewer_js )

If there is any good alternative methods for reflecting the settings, could anyone advice me?

**Comment by slint** [comment]
@yohei-ocean Normally asset bundles are registered via the [`invenio_assets.bundles` entrypoint](https://github.com/inveniosoftware/invenio-previewer/blob/a9f3762d720aaa28c85b76f506445a164061d8b5/setup.py#L112-L122), and this is how `flask npm` knows which packages to include in the produced `package.json`. If you are building a new previewer in your own repository/module that introduces new bundles, you'll have to add the appropriate entry in your `setup.py` (don't forget to run `pip install -e .`, since `setup.py` entrypoint changes aren't automatically picked up)

**Comment by yohei-ocean** [comment]
@slint I forgot to do 'pip install -e .'. Every npm were imported. Thanks your advices.
